import { useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, Check, ChevronRight, CircleUserRound, FileText, Handshake, LayoutDashboard, MapPin, Megaphone, Search, Settings, Users } from "lucide-react";
import { Link, NavLink, Outlet } from "react-router";
import { Btn, Logo, Note, PageHero, SectionHead, StatusTag } from "./components";
import { events, initiatives, members, pages, photos, pillars } from "./data";

export function Home(){
 return <><section className="hero"><img src={photos.hero} alt="People gathering around a boat on a Nigerian waterfront"/><div className="shade"/><div className="shell hero-copy"><span className="eyebrow">Bainbo Taria Awo Club</span><h1>Our heritage.<br/>Our people.<br/><em>Our future.</em></h1><p>Connecting generations, sharing knowledge, creating opportunities and building a lasting legacy.</p><div><Btn to="/join" kind="gold">Join BTA</Btn><Btn to="/community-impact" kind="outline">Explore our initiatives</Btn><Btn to="/support" kind="text">Support BTA</Btn></div></div><aside><b>01</b>A digital home for heritage, knowledge, enterprise and community.</aside></section>
 <section className="section intro"><div className="shell"><div><span className="eyebrow">Who we are</span><h2>A community<br/>built to last.</h2></div><div><p className="lead">Bainbo Taria Awo Club brings people together through shared heritage, knowledge, enterprise and a commitment to community development.</p><p>We create space for generations to connect, learn from one another and build opportunities beyond the present.</p><Btn to="/about" kind="text">Read our story</Btn></div></div></section>
 <section className="stats"><div className="shell">{[["50+","Years of connection"],["500+","Members"],["12","Active programmes"],["8","Community projects"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><small>Illustrative prototype figures</small></section>
 <section className="section model"><div className="shell"><SectionHead eyebrow="The BTA model" title="A current that carries us forward." text="One connected institutional model—from where we come from to what we leave behind."/><div className="model-grid">{pillars.map((x,i)=><div key={x}><small>{String(i+1).padStart(2,"0")}</small><h3>{x}</h3><p>{["Where we came from.","Who we are.","What we learn and share.","How we create opportunities.","How we serve.","What we build from our natural heritage.","Who carries it forward.","What we leave behind."][i]}</p></div>)}</div></div></section>
 <section className="section initiatives"><div className="shell"><SectionHead eyebrow="Featured initiatives" title="What we are building" text="A curated view across knowledge, community, enterprise, heritage and the future of our riverine communities."/><div className="initiative-list">{initiatives.map((x,i)=><Link to={x.path} key={x.title}><b>{String(i+1).padStart(2,"0")}</b><div><StatusTag status={x.status}/><h3>{x.title}</h3><p>{x.summary}</p></div><ArrowRight/></Link>)}</div></div></section>
 <section className="impact"><img src={photos.community} alt="A Nigerian community gathering"/><div><SectionHead light eyebrow="Community impact" title="Goodwill, made measurable." text="We identify needs, assess priorities and deliver with transparent reporting."/><strong>180</strong><span>students reached · illustrative metric</span><Btn to="/community-impact" kind="gold">View community impact</Btn></div></section>
 <section className="section knowledge-home"><div className="shell"><div><SectionHead eyebrow="Knowledge & Ideas Forum" title="Bring an idea. Share knowledge. Start a conversation."/><div className="topics">AI & Technology · Entrepreneurship · Leadership · Health · Aquaculture · Legal Awareness</div></div><Link to="/knowledge/forum" className="featured-session"><span>Featured session · 18 October 2026</span><h3>Understanding Personal Investment in Nigeria</h3><p>With Dr. Tamuno Briggs</p><ArrowRight/></Link></div></section>
 <section className="heritage-home"><img src={photos.elder} alt="Portrait of a Nigerian elder"/><div><SectionHead light eyebrow="The Oral History Project" title="Preserving what we know." text="Recording the stories, experiences and knowledge of our elders before they are lost."/><blockquote>“Every generation holds a part of the story. Our responsibility is to carry it forward.”</blockquote><Btn to="/heritage/oral-history" kind="gold">Explore heritage</Btn></div></section>
 <section className="section events-home"><div className="shell"><SectionHead eyebrow="Events" title="What’s happening at BTA"/><EventList short/><Btn to="/events" kind="text">View events calendar</Btn></div></section>
 <section className="vision-home"><div className="shell"><span className="eyebrow">BTA 2035</span><h2>Looking toward<br/><em>2035.</em></h2><p>A long-term framework for developing people, creating opportunity and preserving what we pass forward.</p><Btn to="/about/bta-2035" kind="gold">Explore the vision</Btn></div></section>
 <section className="partner-home"><div className="shell"><div><span className="eyebrow">Partner with BTA</span><h2>Build something that lasts.</h2></div><p>Partnerships that create measurable value for members, communities and future generations.</p><div><Btn to="/partner">Partner with us</Btn><Btn to="/support" kind="outline">Support BTA</Btn></div></div></section></>
}

function EventList({short=false}:{short?:boolean}){return <div className="event-list">{events.slice(0,short?3:4).map(e=><Link to="/events/knowledge-forum" key={e[2]}><div className="date"><b>{e[0]}</b><span>{e[1]}</span></div><div><small>{e[4]}</small><h3>{e[2]}</h3><p><MapPin size={13}/>{e[3]}</p></div><ArrowRight/></Link>)}</div>}

export function Editorial({kind}:{kind:keyof typeof pages}){const p=pages[kind], image=kind==="heritage"?photos.boats:kind==="blue"?photos.river:undefined;return <><PageHero eyebrow={p[0]} title={p[1]} intro={p[2]} image={image}/><div className="shell"><Note/></div><section className="section editorial"><div className="shell">{p[3].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><div><h2>{x}</h2><p>{p[4][i]}</p><Btn to={kind==="community"?"/community-needs":kind==="partners"?"/partner":"/join"} kind="text">{kind==="community"?"Submit a community need":kind==="partners"?"Start a conversation":"Participate in BTA"}</Btn></div></article>)}</div></section></>}

export function Story(){return <><PageHero eyebrow="Our Story" title="Continuity is our inheritance." intro="A place for BTA’s verified history, milestones, people and records." image={photos.people}/><section className="section"><div className="shell"><Note/><div className="timeline">{[["Origins","A community bound by fellowship and mutual responsibility."],["Growth","A widening network across professions and generations."],["Today","A renewed institution organised around people and service."],["The future","BTA 2035 sets a deliberate path toward legacy."]].map((x,i)=><div key={x[0]}><small>0{i+1}</small><h2>{x[0]}</h2><p>{x[1]}</p></div>)}</div></div></section></>}

export function Governance(){return <><PageHero eyebrow="Leadership & Governance" title="Trust requires accountability." intro="Clear governance, responsible leadership and accessible institutional records strengthen BTA."/><section className="section"><div className="shell"><Note/><SectionHead eyebrow="Institutional documents" title="Governance library"/><div className="docs">{["BTA Constitution","Membership Rules","Code of Conduct","Project Governance Framework","2026 Annual Report","Conflict of Interest Policy"].map((x,i)=><div key={x}><FileText/><span>{i>3?"MEMBERS":"PUBLIC"}</span><h3>{x}</h3><p>PDF · Prototype document</p><button>View document <ArrowRight/></button></div>)}</div></div></section></>}

export function Vision(){return <><PageHero eyebrow="BTA 2035" title="Looking toward 2035." intro="Our long-term framework for a stronger institution and the heritage we pass forward." image={photos.river}/><section className="section"><div className="shell"><Note/><div className="vision-grid">{["Membership","Human Capital","Enterprise","Investment","Community Development","Youth","Women","Aquaculture","Heritage Preservation","Diaspora","Strategic Partnerships"].map((x,i)=><div key={x}><small>{String(i+1).padStart(2,"0")}</small><h3>{x}</h3><p>Develop long-term capacity and measurable value.</p></div>)}</div></div></section></>}

export function BusinessHub(){return <><PageHero eyebrow="BTA Business Hub" title="Buy BTA. Support a BTA business." intro="A prototype member directory for trusted services, expertise and enterprise."/><section className="section"><div className="shell"><Note/><SearchBar/><div className="business-list">{[["Briggs Marine Services","Maritime","Port Harcourt"],["Taria Legal Associates","Legal Services","Lagos"],["Awori Aquaculture","Aquaculture","Rivers State"],["Boma Digital Works","Technology","Abuja"]].map((x,i)=><div key={x[0]}><small>0{i+1}</small><div><h2>{x[0]}</h2><p>{x[1]}</p></div><b>{x[2]}</b><ArrowRight/></div>)}</div></div></section></>}

function SearchBar(){return <div className="searchbar"><Search/><input placeholder="Search by name, expertise or location"/><button>All categories</button></div>}
export function Library(){return <><PageHero eyebrow="Knowledge Library" title="Knowledge, kept in motion." intro="Videos, presentations, articles, session summaries, research and community reports."/><section className="section"><div className="shell"><Note/><div className="library">{[["VIDEO","Building a Career in Technology"],["ARTICLE","Understanding Treasury Bills and Bonds"],["REPORT","Community Water Needs Assessment"],["HERITAGE","Stories from the River"],["PRESENTATION","Starting a Sustainable Enterprise"]].map((x,i)=><Link to="/knowledge/forum" className={i===0?"featured":""} key={x[1]}><span>{x[0]}</span><h2>{x[1]}</h2><p>BTA Knowledge Library · 2026</p><ArrowRight/></Link>)}</div></div></section></>}

export function Detail({type}:{type:string}){const d:Record<string,string[]>={
 forum:["Knowledge Forum","Understanding Personal Investment in Nigeria","A practical session exploring finance, risk and long-term investment choices.","18 October 2026 · Port Harcourt + Online"],
 project:["Community Project","Community School Rehabilitation","A prototype record demonstrating transparent scope, milestones and reporting.","Obio-Akpor · 180 students"],
 event:["Event","BTA Knowledge & Ideas Forum","Members and invited experts sharing practical knowledge.","18 October 2026 · 4:00 PM"],
 article:["News","BTA launches community education initiative","A prototype news article with institutional context.","September 2026 · BTA Communications"],
 oral:["Heritage Programme","The BTA Oral History Project","Recording the stories and knowledge of our elders before they are lost.","Planned · Heritage"],
 centre:["Vision 2035","BTA Blue Economy Centre","A long-term concept for research, training, enterprise and conservation.","Vision 2035 · Not an existing facility"]}[type];return <><PageHero eyebrow={d[0]} title={d[1]} intro={d[2]} image={type==="oral"?photos.elder:type==="centre"?photos.river:undefined}/><section className="section detail"><div className="shell"><article><Note/><h2>About this initiative</h2><p className="lead">{d[2]}</p><p>This page demonstrates the deeper architecture behind the restrained homepage. Verified objectives, activities, evidence and related documents can be managed here.</p><h3>What to expect</h3><ul><li>Clear objectives and responsible ownership</li><li>Current status and milestone updates</li><li>Related events, reports and media</li></ul></article><aside><span className="eyebrow">At a glance</span><h3>{d[3]}</h3><StatusTag status={type==="centre"?"VISION 2035":type==="oral"?"PLANNED":"ACTIVE"}/><Btn to="/join">Express interest</Btn></aside></div></section></>}

export function Events({news=false}:{news?:boolean}){return <><PageHero eyebrow={news?"News & Media":"Events"} title={news?"Stories from across BTA.":"Gather. Learn. Connect."} intro={news?"Institutional news, programme updates and perspectives.":"Meetings, forums and gatherings that keep our community connected."}/><section className="section"><div className="shell"><Note/>{news?<div className="news">{[["Community Impact","BTA launches community education initiative"],["Knowledge","Inside the first BTA Knowledge Forum"],["Heritage","Preserving our heritage"]].map((x,i)=><Link to="/news/community-education" key={x[1]}><img src={[photos.community,photos.people,photos.boats][i]} alt=""/><div><span>{x[0]} · 2026</span><h2>{x[1]}</h2><p>Read the prototype story and context.</p><ArrowRight/></div></Link>)}</div>:<EventList/>}</div></section></>}

function Field({label,wide=false,area=false,type="text"}:{label:string;wide?:boolean;area?:boolean;type?:string}){return <label className={wide?"wide":""}><span>{label}</span>{area?<textarea rows={4} placeholder={`Enter ${label.toLowerCase()}`}/>:<input type={type} placeholder={`Enter ${label.toLowerCase()}`}/>}</label>}
export function Needs(){return <><PageHero eyebrow="Community Needs Register" title="What does your community need?" intro="Make local needs visible for review by the appropriate BTA committee."/><section className="section form-page"><div className="shell"><div><Note/><h2>Submit a community need</h2><p>Submission does not guarantee funding or implementation.</p></div><form onSubmit={e=>e.preventDefault()}><Field label="Location"/><Field label="Nature of problem"/><Field label="People affected"/><Field label="Urgency"/><Field label="Description" wide area/><Field label="Suggested solution" wide area/><Field label="Contact information" wide/><button className="btn primary">Submit community need <ArrowRight size={14}/></button></form></div></section></>}

export function Join({support=false}:{support?:boolean}){const [step,setStep]=useState(0), steps=support?["Choose an area","Your details","Review"]:["Express interest","Application","Review","Confirmation"];return <><PageHero eyebrow={support?"Support BTA":"Membership"} title={support?"Support what lasts.":"Belong. Contribute. Build."} intro={support?"Support community, heritage, youth, scholarships or knowledge.":"Membership is a commitment to fellowship and responsible participation."}/><section className="section join"><div className="shell"><Note/><div className="steps">{steps.map((x,i)=><button className={step===i?"active":""} onClick={()=>setStep(i)} key={x}><span>{i<step?<Check size={14}/>:`0${i+1}`}</span>{x}</button>)}</div><div className="application"><div><span className="eyebrow">Step {step+1} of {steps.length}</span><h2>{support?"How would you like to help?":"Start your membership journey"}</h2><p>This is a prototype flow. No information or payment is submitted.</p></div><form onSubmit={e=>{e.preventDefault();setStep(Math.min(step+1,steps.length-1))}}>{support&&step===0?<div className="choices">{["Community Project","Heritage Preservation","Youth Development","Scholarships","Knowledge Programmes"].map(x=><label key={x}><input type="radio" name="support"/>{x}</label>)}</div>:<><Field label="Full name"/><Field label="Email" type="email"/><Field label="Phone"/><Field label="Location"/><Field label="Message" wide area/></>}<button className="btn primary">Continue <ArrowRight size={14}/></button></form></div></div></section></>}

export function Login(){return <div className="login"><div><img src={photos.boats} alt="Boats on a Nigerian waterfront"/><Logo light/></div><section><div><span className="eyebrow">BTA Members</span><h1>Welcome back.</h1><p>Access meetings, documents, announcements and your BTA network.</p><form><Field label="Member email"/><Field label="Password" type="password"/><Link to="/members" className="btn primary">Sign in to members portal <ArrowRight size={14}/></Link><small>Prototype: use the button to preview the portal.</small></form><Link to="/">← Return to public website</Link></div></section></div>}

const portalNav=[["Dashboard","/members",LayoutDashboard],["Announcements","/members/announcements",Megaphone],["Meetings","/members/meetings",CalendarDays],["Documents","/members/documents",FileText],["Events","/members/events",CalendarDays],["Member Directory","/members/directory",Users],["Knowledge","/members/knowledge",BookOpen],["Mentorship","/members/mentorship",Handshake],["My Profile","/members/profile",CircleUserRound],["Settings","/members/settings",Settings]] as const;
export function MemberLayout(){const [open,setOpen]=useState(false);return <div className="portal"><aside className={open?"open":""}><Logo light/><nav>{portalNav.map(([x,y,I])=><NavLink end={y==="/members"} to={y} key={x}><I size={17}/>{x}</NavLink>)}</nav><Link to="/">← Public website</Link></aside><main><header><button onClick={()=>setOpen(!open)}>Menu</button><div>Prototype member account <b>TD</b></div></header><Outlet/></main></div>}
export function Dashboard(){return <div className="portal-page"><span className="eyebrow">Monday, 14 September 2026</span><h1>Good morning, Taria.</h1><p>Here is what is happening across your BTA community.</p><div className="dash-grid"><div className="next"><span>Next meeting</span><CalendarDays/><h2>BTA General Meeting</h2><p>Saturday, 21 November · 10:00 AM</p><button>View agenda <ArrowRight/></button></div>{[["Announcements","3 new updates",Megaphone],["Documents","12 recent documents",FileText],["Upcoming events","4 events",CalendarDays]].map(([x,y,I]:any)=><div className="dash-card" key={x}><I/><span>{x}</span><h2>{y}</h2><button>Open <ArrowRight/></button></div>)}</div><div className="portal-columns"><section><h2>Recent announcements</h2>{["AGM materials are now available","Mentorship programme applications","Community project volunteer call"].map((x,i)=><div className="announcement" key={x}><span>0{i+1}</span><div><h3>{x}</h3><p>{i+2} days ago · General</p></div><ChevronRight/></div>)}</section><section><h2>Upcoming</h2>{events.slice(0,3).map(e=><div className="mini-event" key={e[2]}><b>{e[0]}<small>{e[1]}</small></b><div><h3>{e[2]}</h3><p>{e[3]}</p></div></div>)}</section></div></div>}
export function PortalPage({type}:{type:string}){const title=type.replace("-"," ").replace(/\b\w/g,c=>c.toUpperCase()), directory=type.includes("directory")||type==="mentorship";return <div className="portal-page"><span className="eyebrow">BTA Members</span><h1>{title}</h1><p>Access current member information and institutional resources.</p><Note/>{directory?<><SearchBar/><div className="member-list">{members.map(x=><div key={x[0]}><b>{x[0].split(" ").map(s=>s[0]).join("")}</b><div><h3>{x[0]}</h3><p>{x[1]} · {x[2]}</p></div><span>{x[3]}</span><button>View profile</button></div>)}</div></>:<div className="resources">{Array.from({length:5}).map((_,i)=><div key={i}><FileText/><div><h3>{type==="documents"?["BTA Constitution","September meeting papers","Impact Report","Membership Rules","Programme update"][i]:`${title} update ${i+1}`}</h3><p>{i+2} September 2026 · Members</p></div><span>MEMBERS</span><ArrowRight/></div>)}</div>}</div>}
